### ISSUE TITLE
右侧sidebar统计信息存在问题

### ISSUE THREAD

**Issue by Motorcure** [renwofei423/tracfullblog#1]
只创建了about时，显示如下
Archive: All posts (0)
No posts.
No authors.
No categories.

存在多个post时，显示如下
Archive: All posts (2)
Browse by time:
二月 2013 (2)
Browse by author:
rss admin (2)
No categories.

也就是统计数量始终少1，而且categories始终没有数据

**Comment by renwofei423** [comment]
侧边统计每日更新一次。

**Comment by Motorcure** [comment]
那是固定在某个时间更新吗？具体的设置在哪个py里面，我刚看了，数据还没更新，我们想把这个时间调整到0点，起码是上班前比较合适些

**Comment by renwofei423** [comment]
你仔细看看cache.py的 _checkTime函数，检查当前时间和缓存文件是否相差大于23小时，大于就更新。
