### ISSUE TITLE
Post shortname不能修改的问题

### ISSUE THREAD

**Issue by Motorcure** [renwofei423/tracfullblog#2]
默认的$USER-%Y/%m/%d/my_topic，同一天发布第二篇时提示Suggestion for new name already exists ('admin-2013/07/04/my_topic'). Please make a new name.，但无法手动输入URL

**Comment by renwofei423** [comment]
你最好是修改blog设置，比如$USER-%Y/%m/%d/%H/%M/%S 这样就不会出现上述情况了。

当然也可惜修改代码，取消URL限定

**Comment by Motorcure** [comment]
很奇怪的是，之前我发布过几篇，是用自定义的URL的，比如about和first，不过已经忘记当初是怎么发布上去的了。。。

另外，如果要修改代码，取消URL限定，大致在哪个位置

**Comment by renwofei423** [comment]
在模板文件fullblog_edit.html中，有这么一段话：
 <input id="blog-name" type="text"
                      name="name" size="40"
                      value="${blog_edit.name or ''}" readonly="readonly"/>
去掉readonly="readonly" 就可以取消URL限定了
